### ISSUE TITLE
Extra ")"'s in example code

### ISSUE THREAD

**Issue by perbrondum** [FormatterKit/PostalCodeValidator#1]
if let validator = PostalCodeValidator(locale: .current) { // United States (US)
    validator.validate(postalCode: "95014")) // true
    validator.validate(postalCode: "22162-1010") // true

    validator.validate(postalCode: "1234567")) // false
    validator.validate(postalCode: "INVALID")) // false
} should be 
if let validator = PostalCodeValidator(locale: .current) { // United States (US)
    validator.validate(postalCode: "95014") // true
    validator.validate(postalCode: "22162-1010") // true

    validator.validate(postalCode: "1234567") // false
    validator.validate(postalCode: "INVALID") // false
}

**Comment by mattt** [comment]
Thanks for pointing this out, @perbrondum. This is fixed by 54ce0d4.
